# --- ETAPA 1: BUILD ---
# Usa uma imagem Node "builder"
FROM node:20-alpine AS builder

WORKDIR /app

# Copia os package.json primeiro para aproveitar o cache
COPY package*.json ./

# Instala todas as dependências (incluindo devDependencies para o build)
RUN npm install

# Copia o resto do código-fonte
COPY . .

# Executa o build do NestJS
RUN npm run build

# --- ETAPA 2: PRODUCTION ---
# Inicia de uma imagem Node limpa e leve
FROM node:20-alpine

WORKDIR /app

# Copia os package.json novamente
COPY package*.json ./

# Instala SOMENTE as dependências de produção
RUN npm install --production

# Copia a pasta 'dist' compilada da etapa 'builder'
COPY --from=builder /app/dist ./dist

# Expõe a porta 3000 (ou a porta que seu NestJS usa)
EXPOSE 3000

# O comando que realmente inicia o servidor
CMD ["node", "dist/main.js"]
